env:
  browser: true
  es2021: true
extends:
  - next/core-web-vitals
  - eslint:recommended
  - eslint-config-prettier
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:prettier/recommended
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  import/order:
    - error
    - alphabetize: { order: 'asc', caseInsensitive: true }
      newlines-between: always
      groups:
        [
          'builtin',
          'external',
          'internal',
          ['parent', 'sibling', 'index'],
          ['object', 'type', 'unknown'],
        ]
      pathGroups:
        - pattern: 'react'
          group: 'builtin'
          position: after
        - pattern: '{next,next/*}'
          group: 'external'
          position: before
        - pattern: '@/**'
          group: 'internal'
          position: before
settings:
  import/resolver:
    typescript: true
    node: true
