env:
  browser: true
  es2021: true
extends:
  - next/core-web-vitals
  - eslint:recommended
  - eslint-config-prettier
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:prettier/recommended
overrides: []
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  import/order:
    - error
    - alphabetize: { order: "asc", caseInsensitive: true }
      newlines-between: always
      groups:
        [
          "builtin",
          "external",
          "internal",
          ["parent", "sibling", "index"],
          ["object", "type", "unknown"],
        ]
      pathGroups:
        - pattern: "@/**"
          group: "internal"
          position: after
        - pattern: "react"
          group: "builtin"
          position: before
        - pattern: "{react*,next*,redux*,@reduxjs/toolkit}"
          group: external
          position: after
settings:
  import/resolver:
    typescript: true
    node: true
    babel-plugin-root-import:
